services:
  - name: Crystal-Auto-Accept-Bot
    type: web
    env: python
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot.py"
    envVars:
      - key: API_ID
        value: "28585290"
      - key: API_HASH
        value: "7e250aaf4f19530d1debaebace4454bc"
      - key: BOT_TOKEN
        value: ""
      - key: DB_URL
        value: ""
      - key: ADMINS
        value: "5593644710"
    regions:
      - singapore  # You can change this based on your preferred region
    httpsOnly: true