services:
  - name: Crystal-Auto-Accept-Bot
    type: web
    env: python3
    plan: free
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python3 bot.py"
    envVars:
      - key: API_ID
        value: <YOUR_API_ID>
      - key: API_HASH
        value: <YOUR_API_HASH>
      - key: BOT_TOKEN
        value: <YOUR_BOT_TOKEN>
      - key: DB_URL
        value: <YOUR_MONGODB_URL>
      - key: ADMINS
        value: "5593644710"
