services:
  - type: web
    name: Crystal-Auto-Approver-Bot
    env: python
    buildCommand: "pip install -r requirements.txt"
    startCommand: "python bot.py"
    plan: free
    envVars:
      - key: API_ID
        sync: true
      - key: API_HASH
        sync: true
      - key: BOT_TOKEN
        sync: true
      - key: DB_URL
        sync: true
    runtime: python